export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_COMPANIES = "GET_COMPANIES";
export const GET_STOCKS = "GET_STOCKS";
export const GET_COMPANYINFO = "GET_COMPANYINFO";
export const GET_CHARTDATA = "GET_CHARTDATA";
export const GET_SENTIMENT = "GET_SENTIMENT";
export const GET_SECTOR_PERFORMANCE = "GET_SECTOR_PERFORMANCE";
export const GET_GAINERS = "GET_GAINERS";
export const GET_LOSERS = "GET_LOSERS";
export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE";

